package:
    type:           yii2-extension
    name:           hisite
    title:          HiSite Yii2 base project
    headline:       HiSite
    keywords:       yii2, hisite, core
    description:    |
        HiSite is a base project for building modular [Yii2] web applications from plugins.

        [yii2]: http://www.yiiframework.com/
