package:
    type:           yii2-extension
    name:           hisite
    title:          HiSite Yii2 base project
    headline:       HiSite
    keywords:       yii2, hisite, core
    namespace:      hisite
    description: |
        HiSite is a base project for building Yii2 sites from components.

        Article describing the idea behind HiSite coming soon...
